apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ../kompose convert -f ../docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: selenium
  name: selenium
spec:
  externalIPs:
  - 10.233.56.92
  ports:
  - name: "4444"
    port: 4444
    targetPort: 4444
  selector:
    io.kompose.service: selenium
status:
  loadBalancer: {}
