---
version: '2'
services:
  selenium-firefox:
    container_name: pv-selenium
    image: selenium/standalone-firefox
    shm_size: 2gb
    volumes:
      - /data:/data
    restart: always

  memcached:
    container_name: pv-memcached
    image: memcached
    restart: always

  backend:
    container_name: pv-backend
    build: backend/
    image: registry.gigabit.nu/pvpoke-visualizer/backend
    restart: always
    volumes_from:
      - selenium-firefox

  frontend:
    container_name: pv-frontend
    build: frontend/
    image: registry.gigabit.nu/pvpoke-visualizer/frontend
    ports:
      - "8000:5000"
    restart: always
    volumes_from:
      - selenium-firefox

  pvpoke:
    image: fredrik84/pvpoke
    container_name: pv-pvpoke
    ports:
      - "80:80"
