---
version: '2'
services:
  selenium:
    container_name: pv-selenium
    image: selenium/standalone-chrome-debug:latest
    volumes:
      - /data:/data
    restart: always

  memcached:
    container_name: pv-memcached
    image: memcached
    restart: always

  backend:
    container_name: pv-backend
    build: backend/
    image: registry.gigabit.nu/pvpoke-visualizer/backend
    restart: always
    volumes_from:
      - selenium
    environment:
      MEMCACHED: memcached:11211
      SELENIUM: selenium:4444
      PVPOKE: pvpoke:80

  frontend:
    container_name: pv-frontend
    build: frontend/
    image: registry.gigabit.nu/pvpoke-visualizer/frontend
    ports:
      - "8000:5000"
    restart: always
    volumes_from:
      - selenium
    environment:
      MEMCACHED: memcached:11211

  pvpoke:
    image: fredrik84/pvpoke
    container_name: pv-pvpoke
    ports:
      - "80:80"
