---
version: '2'
services:
  selenium-firefox:
    container_name: selenium-firefox
    image: selenium/standalone-firefox
    volumes:
      - /dev/shm:/dev/shm
      - /data:/data
    restart: always

  memcached:
    container_name: memcached
    image: memcached
    restart: always

  backend:
    container_name: backend
    build: backend/
    restart: always
    volumes_from:
      - selenium-firefox:ro

  frontend:
    container_name: frontend
    build: frontend/
    ports:
      - "8000:5000"
    restart: always

  pvpoke:
    image: php:7-apache
    ports:
        - "8080:80"
    volumes:
      - "pvpoke/src:/var/www/html"
