apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert -f ../docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - image: registry.gigabit.nu/pvpoke-visualizer/backend
        env:
        - name: MEMCACHED
          value: 10.233.56.91:11211
        - name: SELENIUM
          value: 10.233.56.92:4444
        - name: PVPOKE
          value: 10.233.56.90:80
        name: pv-backend
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: pv-claim0
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
      - name: pv-claim0
        persistentVolumeClaim:
          claimName: pv-claim0
status: {}
