apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert -f ../docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - image: registry.gigabit.nu/pvpoke-visualizer/frontend
        name: pv-frontend
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: selenium-firefox-claim0
      restartPolicy: Always
      volumes:
      - name: selenium-firefox-claim0
        persistentVolumeClaim:
          claimName: selenium-firefox-claim0
status: {}
