apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert -f ../docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: pvpoke
  name: pvpoke
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pvpoke
    spec:
      containers:
      - image: registry.gigabit.nu/pvpoke-visualizer/pvpoke
        name: pv-pvpoke
        resources: {}
      restartPolicy: Always
status: {}
