apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ../kompose convert -f ../docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: pvpoke
  name: pvpoke
spec:
  externalIPs:
  - 10.233.56.90
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: pvpoke
status:
  loadBalancer: {}
