apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose convert -f ../docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: selenium
  name: selenium
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: selenium
    spec:
      containers:
      - image: selenium/standalone-chrome-debug
        name: pv-selenium
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: pv-claim0
      restartPolicy: Always
      volumes:
      - name: pv-claim0
        persistentVolumeClaim:
          claimName: pv-claim0
status: {}
